### ISSUE TITLE
TVDB V4 Doesn't find Battlestar Galactica (2003)

### ISSUE THREAD

**Issue by rytomi** [thetvdb/metadata.tvshows.thetvdb.com.v4.python#10]
I am using Kodi V19. I recently changed scraper from "The TVDB (NEW)" to "The TVDB V4" and everything was found in my library except for Battlestar Galactica (2003). When I switch back to "The TVDB (NEW)" it is immediately found, but again drops when changing back to V4. My folder is named "Battlestar Galactica (2003)" exactly as it's listed on thetvdb.com.

**Comment by KarellenX** [comment]
@rytomi 

Please provide a Kodi debug log that captures you scraping Battlestar Galactica.

**Comment by rytomi** [comment]
Do you still require my debug log?
________________________________

**Comment by antheaezzell** [comment]
Yes, it would be helpful @rytomi

**Comment by KarellenX** [comment]
I remember this problem. I think there were some complaints on the forum about it, and its not limited to Battlestar Galactica.
The show has incorrect dates.

The show on your site is listed as **Battlestar Galactica (2003)**
The first episode is aired as **14 January 2005**
There is already a mismatch there and neither of those dates are correct.

Someone has tried to combine the original Mini-Series which aired in 2003 with the follow-on series which aired in 2004.
It would work if the two mini series episodes were added as S01E01 and S01E02, but they werent and instead were added as Specials.

So you have a tv show tagged as 2003, but the first episode aired as 2005. The scraper is trying to find Battlestar Galactica (2005) and can't.
If I change my folder name to Battlestar Galactica (2005), then the tv show is found correctly by the scraper.

![bg1](https://user-images.githubusercontent.com/44626605/173671496-00612c79-18c6-47ed-8949-264f904b4f71.jpg)

![bg2](https://user-images.githubusercontent.com/44626605/173671532-ee96cfca-4d4c-42e1-a6c0-c1a40ea9f269.jpg)

**Comment by szsori** [comment]
1. Season 1 aired first on Sky1, so our network and airdates for S1 need to be updated to match.
2. That technically makes the series "Battlestar Galactica (2004)", but it's been 2003 from the start so I don't think we want to change it.  Working from the mini-series start date is fine in this, grandfathering it in.
3. The scraper should allow a match if the folder name exactly matches the series title like this.  If it needs to perform an initial search using the folder name, then we should do that.

@KarellenX Can you confirm that the third item should be implemented and should resolve this?  It seems like that's how most scrapers function anyway.  While we're at it, should we also allow direct matching by id (ie "series-73739")?  If so, I'll take that to an internal ticket so we can get that handled.

**Comment by KarellenX** [comment]
>Season 1 aired first on Sky1, so our network and airdates for S1 need to be updated to match.

Will that then bring the aired date back into 2014?
Both IMDB and TMDB have aired dates  18 Oct 2014... https://www.imdb.com/title/tt0407362/episodes?season=1


>That technically makes the series "Battlestar Galactica (2004)", but it's been 2003 from the start so I don't think we want to change it. Working from the mini-series start date is fine in this, grandfathering it in.

ok

>The scraper should allow a match if the folder name exactly matches the series title like this. If it needs to perform an initial search using the folder name, then we should do that.

Yes, if there is an exact match. Some folder names can be quite "inventive", though.

>Can you confirm that the third item should be implemented and should resolve this?

A question better asked of @romanvm , but I don't see why it wouldn't.

>While we're at it, should we also allow direct matching by id (ie "series-73739")?

This was an issue I was going to raise a bit later. It would be good to implement ID searches.
Here is an example of how other scrapers allow it... https://kodi.wiki/view/Add-on:TMDb_TV_Shows#Search
If you could keep the **tvdb/73739** it will reduce the confusion for users, instead of implementing another method.
Also enabling imdb id **tt0407362** search also will be helpful.

**Comment by szsori** [comment]
Yeah, aired dates would get moved back into 2004, which matches some other sources (but not all).  I think it's more accurate since Sky1 is the actual original airing network.

The problem with "tvdb/73739" is that while it can be used in search, it can't be used in directory names.  We now allow direct lookup using any remote id, so perhaps it would be best to completely standardize the approach so it works in both search and directory names?  For example, "tvdb#73739", "imdb#tt0407362", "tmdb#71365", etc.  Or maybe even surround in [ ].  The nice thing about that approach is that people could name it once and really be done with it, so long as the TMDB scraper eventually allowed that in directory names as well.  Thoughts?

**Comment by rytomi** [comment]
When I changed the directory name to Battlestar Galactica (2005) as suggested, TVDB V4 found the title and loaded all the Metadata. From a user perspective, I generally name my folders exactly as it's listed on thetvdb.com, and in this case the disconnect is that the website shows Battlestar Galactica (2003), but (2005) is required to find it.

Does TBDV have the capability to include alternative titles like TMDB does, which would allow it to find the correct series either with (2003) or (2005)?
________________________________

**Comment by szsori** [comment]
@rytomi Aliases should work for matching, but in this case I think we wouldn't want to add other years as aliases.  It will make more sense allowing exact folder matching since that's how everything else works.  This was an excellent issue report... it should allow us to make a pretty significant improvement that we overlooked, so thank you.

**Comment by KarellenX** [comment]
> For example, "tvdb#73739", "imdb#tt0407362", "tmdb#71365", etc. Or maybe even surround in [ ]. The nice thing about that approach is that people could name it once and really be done with it, so long as the TMDB scraper eventually allowed that in directory names as well. Thoughts?

I think there might be a bit of resistance changing the established prefix. I don't think I can speak on behalf of the developers for this. @pkscout @rmrector and @romanvm will need to comment.

I like the idea of the id in the folder name. Universal Movie Scraper also allows this with the **tt000000** ID in the folder name for movies. It was never implemented for other scrapers- reason unknown.

Would it be possible to use the two methods?- your tvdb#73739 in the folder name, then the tvdb/73739 for the manual search string?

Also a Parsing NFO could be used, and it does overcome this problem, but users shouldn't need to go to that extent except in rare cases... https://kodi.wiki/view/NFO_files/Parsing

Thanks @rytomi for confirming the Battlestar Galactica (**2005**)  naming.

**Comment by rmrector** [comment]
Ya, so far I'm not seeing a compelling reason for these in the folder name. That seems more intrusive than putting a URL in an nfo file, if you are going to do something with the file system.

When it comes to movies, scrapers and folder names would also need to contend with the way Kodi cleans the filename and identifies the release year before sending to the scraper.

**Comment by romanvm** [comment]
A scraper does not work with folder names pe se. Folder names are parsed by the Kodi core and then a parsed name and a year (if found) are passed to a scraper. Any change of this internal parsing mechanism will require changes in the Kodi core.

And again, Kodi does have a mechanism of resolving difficult cases, that is,` tvshow.nfo` files. This scraper can resolve URLs to show pages, e.g. https://thetvdb.com/series/battlestar-galactica-2003.

**Comment by szsori** [comment]
I'm missing something.  The Kodi documentation has always said the folder should match the name on the scraping site.

https://kodi.wiki/view/Naming_video_files/Movies

> All files and folders should be simply named with the name of the movie and the year in brackets. The name should match the name shown at the scraper site.

We shouldn't be forcing users to rely on nfo files to resolve issues unless absolutely necessary.  More importantly, BSG matches for this user when on the old scraper but fails with the new.  So what is different that it's unable to perform the match without user intervention?

**Comment by pkscout** [comment]
Just for clarity, the link you've referenced is for Movies, not TV Shows.  But the same mostly applies.  Kodi core parses the folder name and sends back a title and (if included) a year.  What the scraper does with that information is up to the scraper.  For our TMDb TV Show scraper it takes the title and year and uses that to generate a search request via the API and then uses those results to figure out what's next.

I can't speak to why the older version of the TVDB scraper works with BSG and not the new one.  Maybe the scraper dealt with the year differently, or the old API returned something different than the new one does.  That's troubleshooting TVDB will have to do.  Reading the rest of this thread, it would appear that there is differing information about the correct date to use for the show.  Because of that and that "Battlestar Galactica" doesn't uniquely identify a show, the normal solution is for people to use a Parsing Info NFO file to tell Kodi exactly what show to use.

**Comment by romanvm** [comment]
@szsori  I did a quick experiment with stub files:
```
2022-06-16 09:53:41.386 T:46      DEBUG <general>: [metadata.tvshows.thetvdb.com.v4.python (1.1.0)]: about to make request to url https://api4.thetvdb.com/v4/search?year=2003&type=series&limit=10&query=Battlestar+Galactica
2022-06-16 09:53:41.386 T:46      DEBUG <general>: [metadata.tvshows.thetvdb.com.v4.python (1.1.0)]: https://api4.thetvdb.com/v4/search?year=2003&type=series&limit=10&query=Battlestar+Galactica
2022-06-16 09:53:42.101 T:46      DEBUG <general>: [metadata.tvshows.thetvdb.com.v4.python (1.1.0)]: Search results []
```
So you are barking at the wrong tree. Kodi and the scraper do what they are supposed to do. Why the API does not return any results is beyond their control.

**Comment by rytomi** [comment]
Interesting. I do have the specials (mini series and all) included in my folder and the older "TVDB NEW" loaded it up with the specials and all. I'm not home yet, but I'm curious if TBDV V4 will find it correctly with all the specials if I rename to 2005.
________________________________
